### ISSUE TITLE
Error: undefined method `registers' for nil:NilClass

### ISSUE THREAD

**Issue by codytwinton** [jekyll/jekyll-redirect-from#159]
I've been able to successfully install the `jekyll-redirect-from` plugin. However, when I add this to the YML Frontmatter:

```yml
redirect_from: "/terms-conditions"
```

and then run:

```bash
jekyll serve
```

I get this:

```bash
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/iosdev/Developer/Projects/credntia.github.io/_config.yml
            Source: /Users/iosdev/Developer/Projects/credntia.github.io
       Destination: /Users/iosdev/Developer/Projects/credntia.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.5.0 | Error:  undefined method `registers' for nil:NilClass
```

Here's the trace:

``` bash
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/iosdev/Developer/Projects/credntia.github.io/_config.yml
            Source: /Users/iosdev/Developer/Projects/credntia.github.io
       Destination: /Users/iosdev/Developer/Projects/credntia.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/filters/url_filters.rb:44:in `site': undefined method `registers' for nil:NilClass (NoMethodError)
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:58:in `context'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:45:in `set_paths'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:20:in `from_paths'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:26:in `redirect_from'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:27:in `block in generate_redirect_from'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:26:in `each'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:26:in `generate_redirect_from'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:17:in `block in generate'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:15:in `each'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:15:in `generate'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:178:in `block in generate'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:176:in `each'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:176:in `generate'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:72:in `process'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/command.rb:26:in `process_site'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/iosdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/exe/jekyll:13:in `<top (required)>'
	from /Users/iosdev/.rbenv/versions/2.3.1/bin/jekyll:23:in `load'
	from /Users/iosdev/.rbenv/versions/2.3.1/bin/jekyll:23:in `<main>'
```

Here's my current Gemfile.lock

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    colorator (1.1.0)
    ffi (1.9.18)
    forwardable-extended (2.6.0)
    jekyll (3.5.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-feed (0.9.2)
      jekyll (~> 3.3)
    jekyll-redirect-from (0.12.1)
      jekyll (~> 3.3)
    jekyll-sass-converter (1.5.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.14.0)
    liquid (4.0.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    minima (2.1.1)
      jekyll (~> 3.3)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    public_suffix (2.0.5)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.24)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  jekyll-feed
  jekyll-redirect-from
  minima
  tzinfo-data

BUNDLED WITH
   1.15.1
```

**Comment by codytwinton** [comment]
I was able to confirm that this plugin breaks with `jekyll 3.5.0`. Downgrading to `jekyll 3.3.0` resolves the issue temporarily. How would we resolve this issue?

**Comment by pathawks** [comment]
It looks like you are running older versions of a couple gems; could you try running `bundle update`?

**Comment by codytwinton** [comment]
The only gems that were outdated are are `jekyll` (because I downgraded) and `liquid` (because `jekyll 3.3.0` requires an older version of `liquid`. Here's my gem file:

```ruby
source 'https://rubygems.org'

gem 'jekyll', '3.3.0'
gem 'minima'

group :jekyll_plugins do
   gem 'jekyll-feed'
   gem 'jekyll-redirect-from'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by IgnoredAmbience** [comment]
Can also confirm this breaks with the same error when attempting to upgrade to 3.5.0. My trace is identical to the one in the OP.

**Comment by IgnoredAmbience** [comment]
It looks like that Jekyll 3.5 has introduced a new (private) `site` method on the `URLFilters` module that is hiding the `site` accessor defined on `Jekyll::Page`.

**Comment by IgnoredAmbience** [comment]
Quick and hacky patch that seems to get it working again:
```diff
--- /tmp/redirect_page.rb  2017-07-06 13:02:15.734206241 +0100
+++ redirect_page.rb       2017-07-06 13:01:13.557747809 +0100
@@ -2,9 +2,6 @@
 module JekyllRedirectFrom
   # Specialty page which implements the redirect path logic
   class RedirectPage < Jekyll::Page
-    # Use Jekyll's native absolute_url filter
-    include Jekyll::Filters::URLFilters
-
     DEFAULT_DATA = {
       "sitemap" => false,
       "layout"  => "redirect"
@@ -47,13 +44,21 @@
         "permalink" => from,
         "redirect"  => {
           "from" => from,
-          "to"   => to =~ %r!^https?://! ? to : absolute_url(to)
+          "to"   => to =~ %r!^https?://! ? to : AbsoluteURL.new(context).absolute_url(to)                                              
         }                                                                                                                              
       })                                                                                                                               
     end                                                                                                                                
                                                                                                                                        
     private                                                                                                                            
+    class AbsoluteURL                                                                                                                  
+      include Jekyll::Filters::URLFilters                                                                                              
+                                                                                                                                       
+      def initialize(context)                                                                                                          
+        @context = context                                                                                                             
+      end                                                                                                                              
+    end
 
+    private
     def context
       JekyllRedirectFrom::Context.new(site)
     end
```

**Comment by benbalter** [comment]
> It looks like that Jekyll 3.5 has introduced a new (private) `site` method on the `Jekyll::Filters::URLFilters` module that is hiding the `site` accessor defined on `Jekyll::Page`.

Was that fixed by https://github.com/jekyll/jekyll/pull/6163?

**Comment by IgnoredAmbience** [comment]
Yes, this appears to be the same issue.

**Comment by codytwinton** [comment]
@IgnoredAmbience Good to know this is reproducible.

**Comment by bardiharborow** [comment]
Jekyll 3.5.1 has been released. I think this can be closed?

**Comment by codytwinton** [comment]
Awesome!
