### ISSUE TITLE
Broken on Jekyll3: Collection#each should be called on the #docs array directly

### ISSUE THREAD

**Issue by wjdp** [jekyll/jekyll-redirect-from#75]
Getting the following on Jekyll 3.0.0

```
       Deprecation: Collection#each should be called on the #docs array directly.
                    Called by /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:13:in `generate_alt_urls'.
/home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:41:in `is_dynamic_document?': cannot load such file -- jekyll/post (LoadError)
	from /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:47:in `has_alt_urls?'
	from /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:14:in `block in generate_alt_urls'
	from /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:13:in `each'
	from /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:13:in `generate_alt_urls'
	from /home/will/.bundler/ruby/2.1.0/jekyll-redirect-from-0bfa97b3f6f2/lib/jekyll-redirect-from/redirector.rb:8:in `generate'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:154:in `block in generate'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:153:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:153:in `generate'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:58:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:60:in `build'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:35:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
Will push out a fix today. Sorry about this!

**Comment by wjdp** [comment]
No worries, my backlog of fixes from custom plugins etc is much bigger! Thanks for the quick fix
