### ISSUE TITLE
Error:  undefined method `each' for "jekyll-redirect-from":String

### ISSUE THREAD

**Issue by axon-qubes** [jekyll/jekyll-redirect-from#88]
Hi,

After a recent software update, `jekyll-redirect-from` seems to be causing an error which prevents a site from building:

```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
$ gem --version
2.5.0
$ jekyll --version
jekyll 3.0.1
$ jekyll build
Configuration file: /home/user/repo/qubesos.github.io/_config.yml
jekyll 3.0.1 | Error:  undefined method `each' for "jekyll-redirect-from":String
```

And here it is with `--trace`:
```
$ jekyll build --trace
Configuration file: /home/user/repo/qubesos.github.io/_config.yml
/home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems': undefined method `each' for "jekyll-redirect-from":String (NoMethodError)
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

Any ideas? Am I missing something here?

**Comment by parkr** [comment]
In your config file, you have `gems` set to a string instead of an array. Make it 

```
gems:
  - jekyll-redirect-from
```

**Comment by axon-qubes** [comment]
Sorry, I made that change when trying to fix the initial problem. Here it is with the config file set correctly:

```
$ jekyll build --trace
Configuration file: /home/user/repo/qubesos.github.io/_config.yml
/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/user/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/user/.gem/ruby/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
Please see the installation instructions here: http://jekyllrb.com/docs/plugins/#installing-a-plugin
